# [Backend]
backend = "auto"         # Backend to use: "auto", "hyprland", "hyprsunset" or "wayland"
transition_mode = "static"  # Select: "geo", "finish_by", "start_at", "center", "static"

# [Smoothing]
smoothing = true           # Enable smooth transitions during startup and exit
startup_duration = 5       # Duration of smooth startup in seconds (0.1-60 | 0 = instant)
shutdown_duration = 5      # Duration of smooth shutdown in seconds (0.1-60 | 0 = instant)
adaptive_interval = 100    # Adaptive interval base for smooth transitions (1-1000)ms

# [Static config]
static_temp = 4000       # Color temperature for static mode (1000-20000) Kelvin
static_gamma = 50       # Gamma percentage for static mode (10-100%)

